        "infyomlabs/laravel-generator" : "dev-master",
        "infyomlabs/core-templates" : "dev-master",
        "infyomlabs/swagger-generator" : "dev-master",
        "jlapp/swaggervel" : "dev-master",
        "yajra/laravel-datatables-oracle" : "~6.0",
        "laracasts/flash" : "^2.0",
        "cviebrock/eloquent-sluggable" : "^3.1",
        "dflydev/apache-mime-types" : "^1.0",
        "intervention/imagecache" : "^2.3"
